# Generated by Django 4.2.3 on 2023-07-17 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('dropdown', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DropdownLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('links', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Home.link')),
            ],
        ),
    ]
