# Generated by Django 4.2.3 on 2023-07-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dropdownlink',
            old_name='links',
            new_name='link',
        ),
    ]
