# Generated by Django 4.2.3 on 2023-07-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_dropdownlink_href_link_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropdownlink',
            name='href',
        ),
        migrations.AddField(
            model_name='dropdownlink',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
