# Generated by Django 4.2.3 on 2023-07-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_remove_dropdownlink_href_dropdownlink_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='dropdownlink',
            name='text',
            field=models.CharField(max_length=250),
        ),
    ]
