# Generated by Django 4.2.3 on 2023-07-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_dropdownlink_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='route_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
