# Generated by Django 4.2.3 on 2023-07-19 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_link_route_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='href',
        ),
    ]
