# Generated by Django 4.2.3 on 2023-07-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_remove_link_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='route_name',
        ),
    ]
