# Generated by Django 4.2.3 on 2023-07-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_link_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdownlink',
            name='https',
            field=models.BooleanField(default=False),
        ),
    ]
