# Generated by Django 4.2.3 on 2023-07-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_dropdownlink_https'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdownlink',
            name='href',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
