# Generated by Django 4.2.3 on 2023-07-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_alter_dropdownlink_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='link',
            name='https',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dropdownlink',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='dropdown',
            field=models.BooleanField(default=False, verbose_name='Выпадающий список'),
        ),
        migrations.AlterField(
            model_name='link',
            name='href',
            field=models.TextField(default='', verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Текст'),
        ),
    ]
