# Generated by Django 4.2.3 on 2023-07-20 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_game_slug_link_https_alter_dropdownlink_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=250, verbose_name='Название')),
                ('link', models.CharField(max_length=2000, verbose_name='Ссылка')),
                ('image', models.ImageField(upload_to='images/social/')),
            ],
        ),
        migrations.AlterField(
            model_name='dropdownlink',
            name='href',
            field=models.CharField(default='', max_length=2000, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='dropdownlink',
            name='https',
            field=models.BooleanField(default=False, verbose_name='Внешний сайт'),
        ),
        migrations.AlterField(
            model_name='dropdownlink',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Home.link', verbose_name='Главная ссылка'),
        ),
        migrations.AlterField(
            model_name='dropdownlink',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='dropdownlink',
            name='text',
            field=models.CharField(max_length=250, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='link',
            name='href',
            field=models.CharField(default='', max_length=2000, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='https',
            field=models.BooleanField(default=False, verbose_name='Внешний сайт'),
        ),
    ]
