# Generated by Django 4.2.3 on 2023-07-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_genre_game_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
