# Generated by Django 4.2.3 on 2023-07-21 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_delete_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(default='', max_length=1000)),
                ('main_photo', models.ImageField(upload_to='images/game/main_photo/')),
                ('release_date', models.DateTimeField()),
                ('short_description', models.TextField(default='')),
                ('steam_widget', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('languages', models.TextField(default='')),
                ('windows', models.BooleanField(default=True)),
                ('system_requirements_windows', models.TextField(default='')),
                ('system_requirements_windows_recommended', models.TextField(default='')),
                ('macos', models.BooleanField(default=True)),
                ('system_requirements_macos', models.TextField(default='')),
                ('system_requirements_macos_recommended', models.TextField(default='')),
                ('linux', models.BooleanField(default=True)),
                ('system_requirements_linux', models.TextField(default='')),
                ('system_requirements_linux_recommended', models.TextField(default='')),
                ('video', models.CharField(default='', max_length=2000)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.genre')),
            ],
        ),
    ]
