# Generated by Django 4.2.3 on 2023-07-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(),
        ),
    ]
