# Generated by Django 4.2.3 on 2023-07-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_game_video_hd_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='video_poster',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
