# Generated by Django 4.2.3 on 2023-07-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_game_video_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='languages',
        ),
    ]
