# Generated by Django 4.2.3 on 2023-07-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_remove_game_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True, verbose_name='URL'),
        ),
    ]
