# Generated by Django 4.2.3 on 2023-07-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
