# Generated by Django 4.2.3 on 2023-07-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0024_alter_game_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='video_hd_src',
        ),
        migrations.RemoveField(
            model_name='game',
            name='video_poster',
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
