# Generated by Django 4.2.3 on 2023-07-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0025_remove_game_video_hd_src_remove_game_video_poster_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='steam_widget',
            new_name='steam_widget_src',
        ),
        migrations.AlterField(
            model_name='game',
            name='video_src',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
