# Generated by Django 4.2.3 on 2023-07-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0027_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
