# Generated by Django 4.2.3 on 2023-07-30 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0028_multipleimage_delete_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleImage',
        ),
    ]
