# Generated by Django 4.2.3 on 2023-08-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0033_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Logo', 'verbose_name_plural': 'Logo'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='linux',
        ),
        migrations.RemoveField(
            model_name='game',
            name='macos',
        ),
        migrations.RemoveField(
            model_name='game',
            name='system_requirements_linux',
        ),
        migrations.RemoveField(
            model_name='game',
            name='system_requirements_linux_recommended',
        ),
        migrations.RemoveField(
            model_name='game',
            name='system_requirements_macos',
        ),
        migrations.RemoveField(
            model_name='game',
            name='system_requirements_macos_recommended',
        ),
        migrations.RemoveField(
            model_name='game',
            name='system_requirements_windows',
        ),
        migrations.RemoveField(
            model_name='game',
            name='system_requirements_windows_recommended',
        ),
        migrations.RemoveField(
            model_name='game',
            name='windows',
        ),
    ]
