# Generated by Django 4.2.3 on 2023-08-02 08:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0034_alter_logo_options_remove_game_linux_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='short_description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='steam_widget_src',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='game',
            name='video_src',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.CreateModel(
            name='SystemRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_system_name', models.CharField(max_length=250)),
                ('requirements', models.TextField(default='')),
                ('requirements_recommended', models.TextField(default='')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.game')),
            ],
        ),
    ]
