# Generated by Django 4.2.3 on 2023-08-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0035_alter_game_description_alter_game_short_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemRequirement',
            new_name='SystemRequirements',
        ),
    ]
