# Generated by Django 4.2.3 on 2023-08-06 11:42

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0037_alter_systemrequirements_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, default='', unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='images/dynamic_page/')),
                ('text', ckeditor.fields.RichTextField()),
                ('background_color', colorfield.fields.ColorField(default='#282e39', image_field=None, max_length=18, samples=None, verbose_name='Цвет фона')),
            ],
        ),
    ]
