# Generated by Django 4.2.3 on 2023-08-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0044_alter_link_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='slug',
        ),
    ]
