# Generated by Django 4.2.3 on 2023-08-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0045_remove_link_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='dynamic_page',
            field=models.BooleanField(default=False, verbose_name='Динамическая страница'),
        ),
    ]
