# Generated by Django 4.2.3 on 2023-08-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0047_link_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdownlink',
            name='target',
            field=models.BooleanField(default=False, verbose_name='Открывать в новой вкладке'),
        ),
    ]
