# Generated by Django 4.2.3 on 2023-08-06 15:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0049_alter_dynamicpage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='')),
                ('sequence', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, default='', unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/news/')),
                ('text', ckeditor.fields.RichTextField()),
                ('up', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('images', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home.multipleimageupload')),
            ],
        ),
    ]
