# Generated by Django 4.2.3 on 2023-08-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0050_multipleimageupload_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
