# Generated by Django 4.2.3 on 2023-08-07 08:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0051_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, default='', unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/news/')),
                ('short_text', ckeditor.fields.RichTextField()),
                ('text', ckeditor.fields.RichTextField()),
                ('up', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('images', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home.multipleimageupload')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
