# Generated by Django 4.2.3 on 2023-08-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0052_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='main_image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='images',
        ),
    ]
