# Generated by Django 4.2.3 on 2023-08-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0054_rename_multipleimage_multipleimagegame_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleImageNews',
        ),
    ]
