# Generated by Django 4.2.3 on 2023-08-07 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0055_delete_multipleimagenews'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleImageNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.news')),
            ],
        ),
    ]
