# Generated by Django 4.2.3 on 2023-08-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0056_multipleimagenews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multipleimagegame',
            options={'verbose_name': 'MultipleImages Game', 'verbose_name_plural': 'Multiple Images Game'},
        ),
        migrations.AlterModelOptions(
            name='multipleimagenews',
            options={'verbose_name': 'Multiple Images News', 'verbose_name_plural': 'Multiple Images News'},
        ),
        migrations.AlterModelOptions(
            name='systemrequirements',
            options={'verbose_name': 'System Requirements', 'verbose_name_plural': 'System Requirements'},
        ),
        migrations.AlterField(
            model_name='news',
            name='short_text',
            field=models.TextField(default=''),
        ),
    ]
